# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -f
    silent: true

  lint:
    cmds:
      - ansible-lint .
    silent: true

  test:
    cmds:
      - molecule test
    silent: true
